image: bitbucketpipelines/scala-sbt:scala-2.12

options:
  docker: true

pipelines:
  default:
    - step:
        caches:
          - sbt
          - ivy
          - maven
        script:
          - build/get-pip.sh
          - build/get-build-info.py --repo . --info
          - export DOCKER_TAG=`./build/get-build-info.py --repo . --label`
          - echo $DOCKER_TAG
          - sbt update
          - build/gcloud-auth.sh
          - sbt compile
          - sbt test
          - sbt docker:publishLocal
          - build/tag-and-push.sh

definitions:
  caches:
    sbt: ~/.sbt
    ivy: ~/.ivy2